### ISSUE TITLE
I found this in your repo

### ISSUE THREAD

**Issue by Marcelckp** [JobTrack-Jigglypuff/Jobplicity#5]
![T02GLFJMAAW-U02LN3N5REH-e5fd9994845e-192](https://user-images.githubusercontent.com/81308023/153959650-3f186534-a0cc-4ed3-87c6-7b56f40850b4.jpeg)

**Comment by Khin92** [comment]
thank you for visiting our repo. We fixed the issue by saving that pic in our local file 👯 🤣
